load net;
load signs_table;

options = trainingOptions('sgdm', ...
        'MiniBatchSize', 128, ...
        'InitialLearnRate', 1e-3, ...
        'LearnRateSchedule', 'piecewise', ...
        'LearnRateDropFactor', 0.1, ...
        'LearnRateDropPeriod', 100, ...
        'MaxEpochs', 100, ...
        'Verbose', true);
    
% Train an R-CNN object detector. This will take several minutes.    
rcnn = trainRCNNObjectDetector(signs_table, net, options, 'NegativeOverlapRange', [0 0.3], 'PositiveOverlapRange',[0.5 1])

save rcnn;